[note]
filename = "{{slug title}}.{{id}}"
id-charset = "alphanum"
id-length = 5
id-case = "lower"
template = "default.md"

[format.markdown]
# link-format = "[[{{metadata.id}} | {{title}}]]"
# link-format = "[{{title}}]({{path}})"
link-format = "markdown"

[lsp.diagnostics]
# Each diagnostic can have for value: none, hint, info, warning, error

# Report titles of wiki-links as hints.
wiki-title = "hint"
# Warn for dead links between notes.
dead-link = "error"
